### ISSUE TITLE
Update python scripts to python 3

### ISSUE THREAD

**Issue by bjorgve** [MRChemSoft/mrchem#108]
First we need to wait for getkw update.

**Comment by robertodr** [comment]
@bjorgve This should be in `master` already. Can you check?

**Comment by bjorgve** [comment]
I think you might be right, I tired to compile a sample of python codes using python3 without receiving syntax errors. Guess this issue should be closed then?

**Comment by gitpeterwind** [comment]
I noticed a bug in the mrchem python script: for a dry run (mrchem -D) , the output is attempted written to something like "@/my/root/dir/mrchem.inp" .  The @ is problematic and anyway the output should be written without path, as @mrchem.inp is likely to be reused in different directories.

**Comment by robertodr** [comment]
That's bad @gitpeterwind I admit I had not tested the dry run. I'll have a look and push a fix.

**Comment by gitpeterwind** [comment]
I made a small fix, but could not commti because I did not find where the "mrchem" script actually is located, before it is made by make!


    inpfil = os.path.join(root_dir, inpfil_cmd)
    input_dir = os.path.abspath(os.path.join(inpfil, os.pardir))

    # If no input file was passed, assume it's called mrchem.inp
    # and it's located right here.
    if inpfil is None:
        inpfil = os.path.join(root_dir, 'mrchem.inp')
        input_dir = root_dir

    valid_keywords = setup_keywords(input_dir)
    valid_keywords.setkw('printlevel', printlevel)

    if printlevel > 1:
        print("Starting " + sys.argv[0])

    input = getkw.GetkwParser()
    inkw = input.parseFile(inpfil)
    inkw.sanitize(valid_keywords)
    topsect = inkw.get_topsect()
    inkw.run_callbacks(valid_keywords)

    if dryrun:
        xfile = '@' + inpfil_cmd
        with open(xfile, 'w') as fd:
            fd.write(str(inkw.top))

**Comment by robertodr** [comment]
The template file is in [`src/mrchem.in`](https://github.com/MRChemSoft/mrchem/blob/master/src/mrchem.in)

**Comment by gitpeterwind** [comment]
Ah! thanks

**Comment by gitpeterwind** [comment]
Thanks Roberto, seems good!
What I use this for, is to create an input for mrchem.x for use with mpirun. Typically:
`mrchem -D myinput.inp #run beforehand`
`mpirun  mrchem.x @mrchem.inp # in a script`
Therefore it is best the output come in cwd.

**Comment by robertodr** [comment]
@bjorgve @gitpeterwind can this be closed?

**Comment by bjorgve** [comment]
I think we can :+1:
