### ISSUE TITLE
Complex functions

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#113]
It seems to me we need a bit of functionality to handle complex functions more smoothly than we do now. As far as I can see `QMFunctions` now have a real and an imaginary part, which are two `FunctionTree<3>` objects. All the complex arithmetics is handled by the routines in `qmfunctions.cpp`, but at present only for the `Orbital` class.
I need similar functionality for a `Density` class now, because response densities can be complex-valued. Duplicating functionality is not a good idea so I can see two options.

Easy one: move low-level parts of the `Orbital`routines to `QMFunction` routines and then let the corresponding `Orbital` and `Density` classes (or standalone routines) handle the metadata on top.

Difficult one (for me at least): allow MRCPP to handle complex functions the way `QMFunction` does now. `QMFunction` can then have such an object instead of real and imag.

Comment: for this to work smoothly all objects must be created by the derived class routines and the `QMFunction` routines will access them as pass-by-reference. Unless for some fundamental reason this does not work.

Example for the multiplication of two orbitals:

This routine
`Orbital multiply(Orbital inp_a, Orbital inp_b, double prec)`
will: create the output object, handle the metadata, do sanity checks (if necessary) and then call the following routine:
`qmfunction::multiply(prec, out, 1.0, inp_a, inp_a.conjugate(), inp_b, inp_b.conjugate())`
which will handle all the complex-valued arithmetics.

**Comment by ilfreddy** [comment]
@stigrj what do you think?

**Comment by stigrj** [comment]
Closed by #144
