### ISSUE TITLE
Doc build fails on readthedocs

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#128]
And the docs badge still shows success

**Comment by robertodr** [comment]
If the badge says success, who are we to argue? :smile: Jokes apart, can you post the output (or part of it) from the RTD build?

**Comment by stigrj** [comment]
The first error is rather simple, it tries to extract the version number from README.md, but it's not there. We have a VERSION file which currently says X.Y.Z, which is also an error since it expects numbers.

I tried to move past all this but I ran into the old problem I had with building docs locally. Now come to think of it there should be a slack discussion on this...

**Comment by stigrj** [comment]
OK, RTD is up and running again, but the "Classes and functions references" are not picked up. But you are able to build this locally, @ilfreddy?
