### ISSUE TITLE
Problem running MRChem if you have not compiled the code yourself

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#142]
It looks like we have a problem, if the person running MRChem is not the owner of the compiled code. Anders was trying to run some calculations using my MRChem and he gets the following error:

`Error: readSMatrix(), line 30: Failed to open file: /home/luca/programs/mrchem/external/mrcpp/share/mwfilters/I_ph_deriv_1.txt`

I have double checked that he has permission to read those files.

**Comment by ilfreddy** [comment]
I guess the poblem is that we open those files also for writing although we don't really:
This is in the culprit routine:
`std::fstream ifs;`

**Comment by stigrj** [comment]
Does it work if you give write access to those files?

**Comment by ilfreddy** [comment]
Have not tried... but I can try...

**Comment by stigrj** [comment]
Agreed! I was not aware that we ask for write access for those files

**Comment by ilfreddy** [comment]
It should be fairly easy: go from `fstream` to `ifstream` and that's it, as far as I have understood.
