### ISSUE TITLE
Standard output

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#159]
Can we make `mrchem`write by default on an output file instead of `STDOUT`?

Currently to read from `molecule.inp `and write on `molecule.out` i need to do:
`mrchem molecule.inp > molecule.out` 

It would be convenient to obtain the same behavior with: 
`mrchem molecule`

dumping on stdout should still be allowed, but as a (non default) option.

**Comment by stigrj** [comment]
Do we still want this?

**Comment by stigrj** [comment]
Implemented in #299
