### ISSUE TITLE
Unit tests vs integration tests

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#162]
I think we should differentiate between unit and integration tests. As we expand functionality the integration tests will become more and longer, and I'm not sure we should run them all the time. I recently created a Finite Differences (FD) test and a response test. They are both with Li (not exactly a large system...), and the response test does not even run the SCF (it keeps the starting guess as the GS). Still they take 6 min each on my mac.

**Comment by stigrj** [comment]
```
ctest -L unit
ctest -L integration
```

**Comment by bjorgve** [comment]
Do you run the Finite Differences when you do the integration test? I think it would be better to store known results to disk then compare with them

**Comment by ilfreddy** [comment]
I correct myself. It is not a FD calculation but a finite field calculation on Li. Due to symmetry is however enough to compute the polarizability by FD of the (induced) dipole.
