### ISSUE TITLE
Integration tests don't run on stallo

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#164]
All integration tests fail on stallo due to some configuration issue I am not able to solve.
What I have done:
1. compiled a fresh mrchem
2. installed `direnv` manually (downloaded the precompiled 386 executable from the website)
3. run `direnv allow`
4. run `make test`

This is what I get (and it was the same error before points 2-4, which means direnv was uneffective) 

(apologies for the not so nice formatting of the pasted error message...)

`10: Test command: /global/apps/Python/2.7.3/bin/python /home/luca/programs/mrchem/tests/li/test" "--binary=/home/luca/programs/mrchem/build_hess_dft2/bin" "--work-dir=/home/luca/programs/mrchem/build_hess_dft2/tests/li" "--launch-agent" " " "--verbose"
10: Test timeout computed to be: 1500
10: Traceback (most recent call last):
10:   File "/home/luca/programs/mrchem/tests/li/test", line 8, in <module>
10:     from runtest import cli, get_filter, run, version_info  # isort:skip
10: ImportError: No module named runtest
 1/15 Test #10: li ...............................***Failed    0.07 sec
`

**Comment by stigrj** [comment]
`pipenv` solution: activate the environment _before_ `setup`
```
$ cd mrchem
$ pipenv shell
$ ./setup
$ cd build
$ make
$ ctest
```
If the environment is not active at `setup`, only unit tests will run correctly, not the integration tests.
