### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#187]
From @robertodr: We should brainstorm dumping observables in the JSON format sponsored by the MolSSI: https://molssi-qc-schema.readthedocs.io/en/latest/index.html

**Comment by ilfreddy** [comment]
Looks interesting. Would it be a replacement for libGetKw? Or can libGetKw be adapted to use those formats?

**Comment by stigrj** [comment]
A new JSON friendly input parser is in the making, but this issue targets the output rather than input.

**Comment by ilfreddy** [comment]
Nice! But clearly using such formats opens for the possibility of using an output again as an input (as they seem to do with BigDFT as far as I have understood). So the two issues are tightly connected.
