### ISSUE TITLE
[Discussion] Should MRChem rely on EIGEN3_ROOT being set?

### ISSUE THREAD

**Issue by bast** [MRChemSoft/mrchem#19]
See https://github.com/MRChemSoft/mrchem/pull/18.

**Comment by gitpeterwind** [comment]
I tried on the new branch (peter_3), but get already cmake errors at setup. Do I need to change something in Cmake too?

ml notur
source mod_setup.sh
module load CMake
module load Eigen
export EIGEN3_ROOT=/global/hds/software/cpu/eb2/Eigen/3.2.9-foss-2016b
module load Boost
setup --cc=mpicc --cxx=mpic++ --type=release --omp --mpi --prefix=. testeb

gives:
CC=mpicc CXX=mpic++ cmake -DEXTRA_CFLAGS="''" -DEXTRA_CXXFLAGS="''" -DENABLE_MPI=True -DENABLE_OPENMP=True -DENABLE_CODE_COVERAGE=False -DENABLE_TESTS=False -DCMAKE_BUILD_TYPE=release -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="." /global/work/mifapw/Jul2016/mrchem

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/bin/mpicc
-- Check for working C compiler: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/bin/mpic++
-- Check for working CXX compiler: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/bin/mpic++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/lib/libmpi.so  
-- Found MPI_CXX: /global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/lib/libmpi_cxx.so;/global/hds/software/cpu/eb2/OpenMPI/1.10.3-GCC-5.4.0-2.26/lib/libmpi.so  
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Configuring incomplete, errors occurred!
See also "/global/work/mifapw/Jul2016/mrchem/testeb/CMakeFiles/CMakeOutput.log".

CMake Error at /global/hds/software/cpu/eb2/CMake/3.7.1-intel-2016b/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")
Call Stack (most recent call first):
  /global/hds/software/cpu/eb2/CMake/3.7.1-intel-2016b/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/custom/FindEigen3.cmake:80 (find_package_handle_standard_args)
  cmake/custom/eigen.cmake:1 (find_package)
  CMakeLists.txt:35 (include)

**Comment by bast** [comment]
Where can I find your branch?

**Comment by gitpeterwind** [comment]
It is at gitlab

https://gitlab.com/MRChem/mrchem/branches

**Comment by bast** [comment]
Well, my commit https://github.com/MRChemSoft/mrchem/commit/1353479545e26159280cb6d8855cfb4d216badc3 does not seem to be on your branch.

**Comment by gitpeterwind** [comment]
Ah, sorry, I didn't notice that some other change where connected to 
this issue.

Now it is "setting up" fine, thank you!

The compiling does not work, but that seems to be another issue.

**Comment by stigrj** [comment]
Dusting off this old discussion. I suggest to add eigen (as well as an initial guess program) as an external project to mrchem to make it completely self-contained. The goal is to be able to download, compile and run mrchem without any of the annoying dependencies we currently have: eigen, boost (through libgetkw) and lsdalton (in a VERY non-standard version that doesn't even compile anymore). Any thoughts?

MRCPP:
- external projects: catch
- dependencies: eigen
- optional: blas

MRChem:
- external projects: mrcpp, catch, eigen, xcfun, yaml input (to be implemented), initial guess (to be decided)
- dependencies: none
- optional: blas (only through mrcpp)

**Comment by bast** [comment]
I agree with minimizing dependencies. Dependencies really hurt. It will be a relief to get rid of Boost (very difficult dependency). I guess Eigen is a must (?).

**Comment by robertodr** [comment]
Alas, Boost is evil, because it's all or nothing. GetKw only needs `boost::any` and yet it forces anybody downstream at least all of the Boost headers... Eigen is easy. I suggest you switch to modern CMake (and by that I mean 3.3 at the very least) and Eigen 3.3 so you can use [this detection mechanism](http://eigen.tuxfamily.org/dox/TopicCMakeGuide.html) that will propagate Eigen dependencies automatically.

**Comment by robertodr** [comment]
Coming back to the issue of the initial guess. What kind of information do you need? I guess it is the MO coefficient and the basis set. I think it would be fairly straightforward to use [Psi4](http://www.psicode.org/) to generate that information as a [NumPy array](https://docs.scipy.org/doc/numpy/neps/npy-format.html) and then load it into MRChem using the [cnpy](https://github.com/rogersce/cnpy) C++ wrapper to the format (I even have wrappers to directly load into Eigen matrices in the PCMSolver repo). You wouldn't even need to compile Psi4, it would be enough to download the precompiled executable and write a Python input script to get the info you need.

**Comment by stigrj** [comment]
There are several possibilities here. What you describe is exactly how it's done at the moment: MRChem require two input files for the initial guess, one describing the basis set (Dalton format) and one containing the MO coefficients. Then we have our own hacked version of LSDalton to provide these files.

My main issue with such an approach is that it requires a lot of GTO stuff in MRChem that is not useful for anything else than reading these files and projecting the MOs to our MW basis. This part of the code is really ugly and probably grossly inefficient and is better left to the dedicated GTO codes. Also, it's currently only (partially) implemented up to d-functions, and I __really__ don't want to go any further.

What I would like is a more dynamic interface where we get MO function values in arbitrary points *directly* from the initial guess program. For this we would need a more "programmable" GTO code (I was thinking PySCF, but maybe Psi4 is equally good?) or perhaps another numerical code like Dage Sundholm's or Stefan Goedecker's 1D atomic codes. My idea is then to write simple initial guess modules (could be several different) that includes e.g. PySCF and MRCPP as libraries, runs the SCF using PySCF, projects the MOs using MRCPP and writes the MW orbitals to file. Then MRChem reads the MW orbitals directly.

**Comment by bast** [comment]
I also like the solution where MRChem does not need to know the basis set.

**Comment by stigrj** [comment]
Admittedly, my approach is much less straightforward, as it probably requires a proper python interface to MRCPP. But this might be nice to have anyway.

**Comment by bast** [comment]
Yes! Python interface is a great investment. Testing and prototyping greatly simplified.
