### ISSUE TITLE
Error: no operator "<<" matches these op erands

### ISSUE THREAD

**Issue by raullaasner** [MRChemSoft/mrchem#20]
I issued the following commands:

    $ git clone git@github.com:MRChemSoft/mrchem.git
    $ cd mrchem
    $ ./setup --cc=icc --cxx=icpc
    $ cd build
    $ make

The compilation stops with

    [ 11%] Building CXX object C++/CMakeFiles/getkw.dir/Getkw.cpp.o
    /home/raul/builds/mrchem/external/libgetkw/C++/Getkw.cpp(87): error: no operator "<<" matches these operands
                operand types are: std::ostream << std::ostream
      	cout << repr(cout) << endl;

(Full output [here](https://gist.github.com/raullaasner/ebecdab11e54acd456727a971062c78f).)
I'm using Intel Parallel Studio 17.0.2. What could be the reason for the compilation error?

**Comment by stigrj** [comment]
Hi Raul,
I don't think I have encountered this error before. This is an external module we currently use for input parsing, that soon will be removed. Did the other external module (xcfun) compile properly before this one?

**Comment by raullaasner** [comment]
Hi Stig,
The xcfun module compiled successfully. I also tried compiling the libgetwk module separately from [here](https://github.com/juselius/libgetkw), but I got the same error. Which compiler version are you using? I should try the same compiler.

**Comment by stigrj** [comment]
I've been using Intel 13.0.1 and GNU 4.9.1. I anticipate, however, further complications down the line, as libgetkw still has some unresolved boost dependency. We removed boost completely from the main code some time ago, but I didn't realize that libgetkw still depended on it. This is the reason I'm currently looking for a replacement to libgetkw. If you have boost installed on your system you might be able to link it manually, otherwise I would wait for an update

**Comment by raullaasner** [comment]
I have linked boost to libgetkw, but the error is still there. I'll wait for an update then. Thanks!

**Comment by robertodr** [comment]
You might want to try to patch up Getkw [like this](https://github.com/juselius/libgetkw/blob/pcmsolver/C%2B%2B/Getkw.cpp#L85-L88)
@stigrj  for a quick, transitional patch, while de-Boosting: as far as I recall Getkw depends only on Boost.Any, which is header-only and might be brute-force copy-pasted into your repo. If you are planning to rewrite input parsing @bast and I would suggest using YAML format.

**Comment by stigrj** [comment]
Thanks @robertodr, I will do the dirty fix first. Btw, do you have any experience with [yaml-cpp](https://github.com/jbeder/yaml-cpp)?
 However, the error in this issue is not related to boost. @raullaasner, did you try with an older compiler?

**Comment by robertodr** [comment]
No, no experience with that library. The problem reported is due to differences in the implementation of the C++ standard in different compilers and should be fixed by the patch I linked to in the previous comment.

**Comment by stigrj** [comment]
@robertodr: unfortunately boost/any.hpp includes a number of other boost files, so the dirty copy-paste became too complicated... @raullaasner: I have tried out a couple of different compilers (up to Intel 2016), but I'm still unable to reproduce your original compilation error. I have still updated libgetkw with the patch suggested by @robertodr, so your error is hopefully gone now. You will still have to link to boost manually, though. Unfortunately, I probably won't have time to replace getkw with YAML any time soon...

**Comment by raullaasner** [comment]
It seems to get past that point now. The compilation is now terminated with the message

    /home/raul/builds/mrchem/src/mrcpp/parallel.cpp: In instantiation of ‘void Rcv_SerialTree(FunctionTree<D>*, int, int, int, MPI_Comm) [with int D = 1; MPI_Comm = int]’:
    /home/raul/builds/mrchem/src/mrcpp/parallel.cpp:467:104:   required from here
    /home/raul/builds/mrchem/src/mrcpp/parallel.cpp:104:9: error: ‘class SerialFunctionTree<1>’ has no member named ‘sNodesCoeff’; did you mean ‘sizeNodeCoeff’?
      STree->sNodesCoeff = STree->nodeCoeffChunks[ichunk];
    ~~~~~~~^~~~~~~~~~~

Full output here [here](https://gist.github.com/raullaasner/ebecdab11e54acd456727a971062c78f). It looks like a simple API clash.

**Comment by stigrj** [comment]
Alright, you're at least past getkw! :) Try to disable MPI, it is currently not stable (keep OpenMP, though).

**Comment by raullaasner** [comment]
Thanks. I managed to install and successfully run one of the examples.
