### ISSUE TITLE
Tag older subproject version

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#208]
It is currently only possible to tag the latest upstream version of a subproject (tested both MRCPP and XCFun) in the superbuild. When the subproject sources are fetched there's only a single entry in its git log (the latest) which makes it impossible to checkout an older version at that point.

This is the reason all CircleCI builds fail at the moment, since upstream MRCPP has been updated while MRChem points to an older version.

**Comment by robertodr** [comment]
You need to remove `GIT_SHALLOW 1` to get the whole history. I went for a shallow clone to avoid spending ages downloading subprojects at configuration. However, if you need to work with both super- and subprojects, I'd advise to install the subprojects separately and let the superproject pick up the installed one. I know it's a pain, especially coming from the previous set up, but it keeps things cleaner. Additionally, the remote for the subprojects is anonymous HTTPS, which means you'll have a little trouble pushing any changes.

**Comment by stigrj** [comment]
Yes, that's fine, but the reason to add a `GIT_TAG` at all is for reproducibility, so that we can point to an older version of the subproject. I don't see much point in tagging a git revision if only the latest version is possible, then we should just use `master`, e.i. a moving target? I guess it will be different if we use proper tags for versions, that all tags and branches still show up with `GIT_SHALLOW 1`?

**Comment by robertodr** [comment]
Then I misunderstood what you meant, apologies. `GIT_TAG` checks out the given revision/branch/tag. `GIT_SHALLOW 1` will only get the latest commit pointing to that "tag", so no history. The revisions currently figuring in the various `fetch_*.cmake` modules are the minimum required "versions" of the various modules that can work properly with the superbuild. Subprojects earlier than that will only work by first installing them and then letting MRChem pick them up (`-DMRCPP_DIR=...` and so forth) and _not_ with the superbuild.

**Comment by robertodr** [comment]
The reason to _not_ follow `master` is, as you said, that it's a moving target. Now we are on `master` but at a specific commit.

**Comment by stigrj** [comment]
Hmm, but this doesn't work exactly as expected then, since it is not able to checkout an older revision directly. Whenever the `GIT_TAG` points to a commit that is not the latest on `upstream/master` it fails with
`fatal: reference is not a tree: c402ecb...` 

Looks like it works something like this under the hood:
```
git clone git@github.com:MRChemSoft/mrcpp.git  (shallow clone, only latest commit)
git checkout <older-git-revision> (error, since git history is empty)
```

**Comment by robertodr** [comment]
Is this a clean configuration? Or a rebuild after changes?

**Comment by robertodr** [comment]
The logs for the fetch operations can be found here: `<build-dir>/mrcpp_sources-subbuild/mrcpp_sources-populate-prefix/tmp/mrcpp_sources-populate-gitclone.cmake`

**Comment by stigrj** [comment]
But the shallow clone will probably provide all branches and tags. It's just the combination `GIT_SHALLOW 1` with `GIT_TAG <git-revision>` that doesn't work.

It fails in a clean configuration, also on CI.

**Comment by robertodr** [comment]
There must be leftovers somewhere... Or the history was rewritten? @bast any ideas?

**Comment by stigrj** [comment]
It does happen in two steps, first shallow clone, then checkout. From `mrcpp_sources-populate-gitclone.cmake`:
```
# try the clone 3 times in case there is an odd git clone issue
set(error_code 1)
set(number_of_tries 0)
while(error_code AND number_of_tries LESS 3)
  execute_process(
    COMMAND "/usr/bin/git" ${git_options} clone ${git_clone_options} --origin "origin" "https://github.com/MRChemSoft/mrcpp.git" "mrcpp_sources-src"
    WORKING_DIRECTORY "/home/stig/src/mrchem-stig/build-omp"
    RESULT_VARIABLE error_code
    )
  math(EXPR number_of_tries "${number_of_tries} + 1")
endwhile()
if(number_of_tries GREATER 1)
  message(STATUS "Had to git clone more than once:
          ${number_of_tries} times.")
endif()
if(error_code)
  message(FATAL_ERROR "Failed to clone repository: 'https://github.com/MRChemSoft/mrcpp.git'")
endif()

execute_process(
  COMMAND "/usr/bin/git" ${git_options} checkout 16da6e17742b3d6a2e0b1517f91ee086c0bd828a --
  WORKING_DIRECTORY "/home/stig/src/mrchem-stig/build-omp/mrcpp_sources-src"
  RESULT_VARIABLE error_code
  )
if(error_code)
  message(FATAL_ERROR "Failed to checkout tag: '16da6e17742b3d6a2e0b1517f91ee086c0bd828a'")
endif()
```

**Comment by stigrj** [comment]
If I remove `GIT_SHALLOW 1` it works. Perhaps that's just the way to go?

**Comment by bast** [comment]
IIUC you try to fetch https://github.com/MRChemSoft/mrcpp/commit/c402ecb but this really does not exist (?)

**Comment by stigrj** [comment]
The `c402ecb` was actually from `dftlibs/xcfun`

**Comment by bast** [comment]
OK - sorry I read too quick.

**Comment by stigrj** [comment]
Actualy, I mixed xcfun and mrcpp in my comments above :slightly_smiling_face:

But it's the same both for mrcpp and xcfun. If I point to a git revision that *does* exist but is not the latest, it won't find it if I use `GIT_SHALLOW 1`

**Comment by robertodr** [comment]
Sure, we can remove `GIT_SHALLOW  1` (though I'd keep for Eigen since their history is slightly larger) But this makes _no sense_, to me at least, with CMake's docs...

**Comment by bast** [comment]
But the CMake docs say "Use when GIT_TAG is not specified":
https://cmake.org/cmake/help/v3.6/module/ExternalProject.html

**Comment by robertodr** [comment]
Eh, you did know I am an idiot :man_facepalming:, didn't you?
