### ISSUE TITLE
MRChem driver

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#214]
Problem
----------
The current setup of the MRChem driver is a single executable `mrchem.x` which goes directly into the `SCFDriver` class which
1. Reads the input
2. Figures out which calculations to run
3. Initializes all necessary components and solvers
4. Runs the calculations (initial guess, SCF and possibly several response calculations)
5. Collects the requested output

It is now very difficult to follow all the different setups and initializations in the `SCFDriver` and the subsequent SCF iterations which are hidden in the `SCF`, `GroundStateSolver`, `OrbitalOptimizer`, `LinearResponseSolver` etc. classes.

Possible solution
---------------------
Divide the program into a set of completely separate modules (i.e. executables), each of which is responsible for a particular part of the calculation and communicates with the other modules through files (this is e.g. the setup of the ORCA program). Currently we would have the following modules
1. Initial guess: `sad-guess.x`, `gto-guess.x` etc
2. Ground state SCF: `scf.x`
3. Linear response SCF: `linear-response.x`
4. Possibly separate modules for computing properties from converged orbitals

Then we would have a simpler Python driver on top (the current `mrchem` script) which calls the different executables. The `scf.x` module would e.g. be the current `SCFDriver` and `OrbitalOptimizer` combined into a simpler and much more comprehensible piece of code, and its interface strictly defined as MW orbitals in -> MW orbitals out. (Actually, the initial guess modules are already implemented and available)

Pros
------
- Modularity == great
- Simpler implementation
- Simpler integration testing
- Facilitates checkpointing/restarting of calculations
- Facilitates geometry optimization (looping over `scf.x`)

Cons
------
- Significant (?) overhead from unnecessary file I/O
- Potentially very large disk requirements if **all** orbitals **has** to be written to disk **every** time
- Overhead from repeated initializations, e.g. operators has to be reconstructed in each module

**Please** give feedback. Is it sustainable to write orbitals to disk (think a calculation with 500 orbitals on 5000 cores)? Can we accept the extra overhead? Can you think of alternatives?

**Comment by ilfreddy** [comment]
This reminds me of the way Gaussian is set up, with several "links" doing different things. However I would hardly consider Gaussian an example of "modern" programming (hope Giovanni will never read this...).
Would it not be possible to separate logically the different parts, still without using different executables?
So instead of `sad-guess.x` or `scf.x` have `SCFDriver.cpp` `LinearResponseDriver.cpp` `InitialGuessDriver.cpp` `GeometryDriver.cpp`

I agree at any rate that the current `SCFDriver.cpp` is past its expected lifetime :-)

**Comment by robertodr** [comment]
I would also vote for Luca's solution, _i.e._ separate the driver into smaller source files. The question of transferring information is however still relevant, both for "finial quantities", such as energies and property tensors, and "intermediates", such as orbitals. For the former I think JSON would be nice, for the latter zipped NumPy or HDF5.

**Comment by stigrj** [comment]
The `SCFDriver` has turned into the `mrchem::driver` namespace and has been significantly simplified since this issue was raised. We'll keep a single executable, but possibly decompose the driver if necessary, as suggested
