### ISSUE TITLE
PeriodicTable vdW radii units

### ISSUE THREAD

**Issue by Gabrielgerez** [MRChemSoft/mrchem#222]
There seems to be an issue with the vdW radii of several elements in `PeriodicTable.cpp`.
The units of these radii should be made more clear and in some cases revised.

**Comment by robertodr** [comment]
Feel free to copy from here: https://github.com/PCMSolver/pcmsolver/blob/master/src/utils/Atom.cpp These are in ångström. References for the radii here https://pcmsolver.readthedocs.io/en/stable/users/input.html#cavity-section-keywords, under "RadiiSet"

**Comment by Gabrielgerez** [comment]
Should i make a pull request to any edits i do to `PeriodicTable.cpp`?
