### ISSUE TITLE
Polarizability tensor not printed with high prec

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#225]
Anders found something weird. The polarizability tensor is not printed (maybe not even computed) when high prec calculations are performed. Everything looks fine in low prec (rel_prec=10-4 orbital_prec=10-3), at intermediate prec (rp 10-5 op 10-4) only one row is computed/shown and at high prec (rp 10-6 op 10-5) the whole tensor is printed as zero.

So far no idea what could be the reason.

It is of course annoying to debug if it only shows at high prec :-(

**Comment by ilfreddy** [comment]
Update: a given tensor row is printed as ZERO if the corresponding response equation did not converge. It might be a good idea to also print a warning in that case.

**Comment by stigrj** [comment]
Fixed with #270
