### ISSUE TITLE
All response and no properties make MRChem a dull program  ;-)

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#241]
Premises:
1. A response calculation reading orbitals from input and performing no SCF
2. No properties requested which only require an expectation value (such as dipole moment)
Result: code crashes in `calc_scf_properties` because the required JSON section is empty
Quick fix: add dipole moment among the required properties
Note: the crash happened only when `MRChem` was compiled in `debug` mode. The empty secton was silently ignored in `release` mode.

**Comment by stigrj** [comment]
Fixed
