### ISSUE TITLE
Quotes removed in setup_command

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#261]
The setup command line of each build is stored in `setup_command` for future reference. However, when more than one option is passed to `cmake` via the `--cmake_options` flag, the sting is stored without hyphens `--cmake_options=-Doption_a -Doption_b`. The right command line should contain `--cmake_options='-Doption_a -Doption_b'`.
I guess it has to do with the handling of such a string by python.

**Comment by robertodr** [comment]
I think we hit this problem 2-3 years ago with @bast and the conclusion was that it's actually the shell that handles quotes, not Python. So it's next to impossible to do what you ask in a consistent manner.

**Comment by ilfreddy** [comment]
Can we put a "reminder" in a separate line?

Something like:

`./setup option option option`
`WARNING: remember to add missing quotes if necessary``

It would spare us some time, considering that we will eventually forget that, given that it happens with the frequency of a leap year.

**Comment by bast** [comment]
This is where we already wrestled with it: https://github.com/dev-cafe/autocmake/issues/169

**Comment by ilfreddy** [comment]
What I suggest as a "patch" is simply to append the `WARNING` line in the file `setup_command`. This should be doable, or?

**Comment by bast** [comment]
Warning is definitely doable. I will again look at this issue.

**Comment by ilfreddy** [comment]
But don't work in shifts for it, OK? ;-)

**Comment by robertodr** [comment]
> But don't work in shifts for it, OK? ;-)

We have a team on it.

**Comment by bast** [comment]
There is a solution: https://github.com/dev-cafe/autocmake/pull/264 - once this is in, it will require that you regenerate `setup`.

**Comment by robertodr** [comment]
@ilfreddy Radovan's fix in dev-cafe/autocmake#264 has now been merged. You should regenerate 
the `setup` script:
```
cd cmake
python update.py --self
python update.py ..
```
and try again.

**Comment by stigrj** [comment]
Fixed by #291
