### ISSUE TITLE
XCFun bug in VWN3 functional for the spin-polarized case

### ISSUE THREAD

**Issue by robertodr** [MRChemSoft/mrchem#301]
@bast fixed a bug for spin-polarized VWN3 in XCFun, which was based on the C implementation in Dalton so we need to double-check this also here.

The problem only showed up when alpha and beta densities differed.

Issue: https://github.com/dftlibs/xcfun/issues/132 Fix: https://github.com/dftlibs/xcfun/pull/134

**Comment by stigrj** [comment]
Fixed in #302
