### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by ilfreddy** [MRChemSoft/mrchem#34]
We should update and maintain our test suite.
1) Make sure the tests we have now are properly functioning. We do have a "tests" folder based on the CTest infrastructure, but I'm unsure how many of those tests are still valid in the current code. Moreover when I run "ctest -N" in the build folder it gives zero available tests
2) Progressively add testing functionality
Make sure that a wider portion of the code is being tested
3) Add build images on Travis both for linux and for mac.
We should not add too many IMO. I guess 4-5 will do to start with, otherwise the task of maintaining them will be overwhelming

**Comment by stigrj** [comment]
The automated testing is now up and running (PR #74 ) with the following builds:

- Parallel run release mode
- Sequential run release mode
- Sequential run debug mode w/ code coverage

 Can someone (@ilfreddy ) with a mac add at least one mac build?

**Comment by stigrj** [comment]
I think we can close this one now, the test suite is up and running with both unit and integration tests, although the coverage could be a bit better
