### ISSUE TITLE
Add shared library and soversion

### ISSUE THREAD

**Issue by susilehtola** [MRChemSoft/mrchem#390]
mrchem appears to produce only a static library at the moment, even when compiled with `-DBUILD_SHARED_LIBS:BOOL=ON`.

Please make mrchem behave like mrcpp by building a shared library with a soname.

**Comment by robertodr** [comment]
The library is built as an intermediate step to `mrchem.x` and `unit_tests.x` It's not meant to be packaged and distributed. I'll change how we do things so that there's only executables produced.

**Comment by susilehtola** [comment]
> The library is built as an intermediate step to `mrchem.x` and `unit_tests.x` It's not meant to be packaged and distributed. I'll change how we do things so that there's only executables produced.

OK, fine.
