### ISSUE TITLE
Questionable radii in periodictable.py

### ISSUE THREAD

**Issue by Gabrielgerez** [MRChemSoft/mrchem#419]
There is no specification on where the radii here come from and what units they are

**Comment by robertodr** [comment]
Can we change them to the Bondi-Mantina set?

**Comment by stigrj** [comment]
Can this be fetched from QCElemental, like @Andersmb did for the physical constants?

**Comment by robertodr** [comment]
Yes, that would work: they use Bondi-Mantina values for van der Waals radii. However, in PCM one needs to use 1.2 for hydrogen  instead of 1.1 in the Bondi-Mantina table. I guess it's easy to fix in `validate_cavity` though.
