### ISSUE TITLE
KAIN is slightly off in MPI

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#43]
For real this time (I think) :)
Without KAIN the two solutions (MPI and OMP) are identical throughout, but with KAIN they start to diverge slightly from iteration 3 (when KAIN first takes effect). The MPI/KAIN version isn't completely off, but it takes a few more iterations to converge than OMP/KAIN, and the solutions are equal only within the convergence threshold.

**Comment by gitpeterwind** [comment]
The first MPI-KAIN iteration is getting the right result, but not after.
The  test (orbitals.size() == fock.size()) is failing because fock.size()=0. Where is this fock vector constructed?
It is not very easy to search for "fock" as this has many meaning/types in different parts of the codes...

**Comment by stigrj** [comment]
The Fock matrix is currently not used in the KAIN solver as it is computed explicitly in each iteration (i.e. it should be zero).

**Comment by gitpeterwind** [comment]
OK, then it is something else. Do you have any proposition of where else KAIN mixes several orbitals?
All parts that involves more than one orbital (mwtrees only, the matrixes are computed entirely for each MPI) must be adapted.
For instance are energies computed elsewhere than in FockOperator.cpp?

**Comment by stigrj** [comment]
I'm looking into this now...

**Comment by stigrj** [comment]
I'm looking into this now...
