### ISSUE TITLE
Include Eigen3 project

### ISSUE THREAD

**Issue by susilehtola** [MRChemSoft/mrchem#79]
The header-only Eigen3 library is necessary to build mrchem, so it could be imported as a git repository like libgetkw and xcfun.

https://github.com/eigenteam/eigen-git-mirror

**Comment by stigrj** [comment]
Yes, we have briefly discussed this. I'm in favor of including it and making MRChem completely self-contained, but I seem to recall some reluctance by others. @robertodr ?

**Comment by robertodr** [comment]
No objections here. The indecision was between having a static copy, a submodule or downloading at compile-time.

**Comment by stigrj** [comment]
Ok great! Any preference among the three?

**Comment by robertodr** [comment]
The quick'n'easy is as a submodule, which is also consistent with xcfun and libgetkw. Download at compile-time within a superbuild is my personal preference, but that can be arranged later on.

**Comment by stigrj** [comment]
Fixed ages ago
