### ISSUE TITLE
Hybrid DFT

### ISSUE THREAD

**Issue by stigrj** [MRChemSoft/mrchem#97]
The `exact_exchange` factor (e.g. 20% for B3LYP) is apparently not picked up, so we always get full HF exchange. Could also be that the corresponding 80% factor is not passed correctly to XCFun. In any case we get way too much exchange in hybrid calculations.

**Comment by ilfreddy** [comment]
Can you upload an input file? I can try to have a look at it.

**Comment by stigrj** [comment]
Just change the He or Li example to
```
DFT {
  exact_exchange = 0.25
$functionals
PBEX    0.75
PBEC    1.00
$end
}
```
and compare with the elephant PBE0.

**Comment by stigrj** [comment]
I removed the `x_factor` internal parameter in `ExchangePotential` and replaced it with an external multiplicative factor used in the `FockOperator`
```
F = T + V_nuc + J + V_xc - alpha*K
```
This might have been a bad idea if the `alpha` parameter is not carried around correctly in the calculation, so maybe we should put it back into `ExchangePotential`.

**Comment by ilfreddy** [comment]
Are you really doing it. I don't see any factors here:
`    if (this->kin  != 0) this->T += *this->kin;
    if (this->nuc  != 0) this->V += *this->nuc;
    if (this->coul != 0) this->V += *this->coul;
    if (this->ex   != 0) this->V -= *this->ex;
    if (this->xc   != 0) this->V += *this->xc;
``

**Comment by stigrj** [comment]
Hmm, maybe that solves it

**Comment by stigrj** [comment]
Yes, it *should* be correct if you add the parameter to the constructor and do
```
        RankZeroTensorOperator &K = (*this);
        K = x_fac * (*exchange);
```

**Comment by ilfreddy** [comment]
Done! I need to test that it works but I have to leave now. Later...

**Comment by stigrj** [comment]
Fixed
